from typing import Optional

from domain.entities.department_entity import DepartmentEntity


class IDepartmentRepository:
    def get_list_departments(
        self, page: int, page_size: int, search: str, is_active: Optional[bool]
    ) -> list[DepartmentEntity]: ...

    def get_department_by_id(self, id: int) -> DepartmentEntity | None: ...

    def get_department_by_name(self, name: str) -> DepartmentEntity | None: ...

    def create_department(self, department: DepartmentEntity) -> bool: ...

    def update_department(self, department: DepartmentEntity) -> bool: ...

    def update_status_department(self, department: DepartmentEntity) -> bool: ...

    def is_department_in_use(self, department: DepartmentEntity) -> bool: ...
